# .github/workflows/render-deploy.yml

name: Deploy to Render and Log to GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write

    steps:
      # Step 1: Start the deployment
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production # The environment is defined here

      # Step 2: Trigger the deployment on Render
      - name: Trigger Render Deploy
        run: |
          curl --fail-with-body -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

      # Step 3: Finish the deployment
      - name: Update GitHub Deployment Status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.id }}
          env_url: https://your-app-name.onrender.com
          env: ${{ steps.deployment.outputs.env }} # ADD THIS LINE
